repos:
  - repo: https://github.com/TekWizely/pre-commit-golang
    rev: master
    hooks:
      -   id: go-fmt
          args: [ -w , -s ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0  # Use the ref you want to point at
    hooks:
      -   id: trailing-whitespace
      -   id: mixed-line-ending
          args: [ --fix=lf ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.931'
    hooks:
    -   id: mypy
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

  - repo: https://github.com/ambv/black
    rev: 22.1.0
    hooks:
    - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
