[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = 'black'

[tool.black]
line-length = 88
include = '.pyi?$'
exclude = '''
/(
    .git
    | .mypy_cache
    | _build
    | build
    | dist
)/
'''
