name: "Docker Build - Base GPU Image"

on:
  push:
    branches:
      - "stable"
  pull_request:
    branches:
      - "stable"
  schedule:
    # Weekly, at 04:00 on Monday UTC time
    - cron: "0 4 * * 1"
  workflow_dispatch:

jobs:
  gpu-base:
    uses: ./.github/workflows/build-jupyter-workflow.yml
    with:
      image: gpu-base
    secrets:
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
