name: Publish to PyPI

on:
  push:
    tags:
      - v*
jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./hypertrain
    steps:
    - uses: actions/checkout@master

    - uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install pypa/build
      run: |- 
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Build Hypertrain package
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |-
        python setup.py sdist bdist_wheel
        twine upload dist/*
