name: Publish to PyPI

on:
  push:
    branches:
      - stable

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./hypertrain
    steps:
    - uses: actions/checkout@master
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install pypa/build
      run: |-
        python -m
        pip install
        build
        --user

    - name: Build Hypertrain package
      run: |-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/

    - name: pypi-publish
      uses: pypa/gh-action-pypi-publish@717ba43cfbb0387f6ce311b169a825772f54d295
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages_dir: hypertrain/
        print_hash: true

