# .github/workflows/module1.yml
name: Release cli

on:
  pull_request:
    paths:
      - hyper/**
  push:
    paths:
      - hyper/**
    branches:
      - stable

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history

      - name: Git Version
        uses: codacy/git-version@2.2.0
        with:
          prefix: hyper-
          log-path: hyper/
          release-branch: stable