name: Secret Scan

on:
  push:

jobs:
  secret-scan:
    uses: gohypergiant/.github/.github/workflows/secret-scan.yml@stable
    with:
      exclude_path: .github/config/secret_scan_exclude_paths.txt
